import { NextResponse } from 'next/server';
import clientPromise from '@/lib/db';
import { verifyToken } from '@/lib/auth';

export async function GET(request) {
  const token = request.cookies.get('token')?.value;
  const decoded = verifyToken(token);

  if (!decoded || !decoded.affiliate_name) {
    return NextResponse.json({ error: 'Unauthorized access.' }, { status: 401 });
  }

  const affiliateName = decoded.affiliate_name;

  try {
    const client = await clientPromise;
    const db = client.db(process.env.DATABASE_NAME);
    const transactions = db.collection('transactions');

    // 1. Total Volume Generated by this Network
    const totalResult = await transactions.aggregate([
      { $match: { affiliate_name: affiliateName } },
      { $group: { _id: null, total: { $sum: '$total_sol' } } }
    ]).toArray();
    const totalVolume = totalResult[0]?.total || 0;

    // 2. Personal Earnings (from their own bots)
    const personalEarningsResult = await transactions.aggregate([
      { $match: { affiliate_name: affiliateName, payer_type: 'affiliate_own' } },
      { $group: { _id: null, total: { $sum: '$wallet1_sol' } } }
    ]).toArray();
    const personalEarnings = personalEarningsResult[0]?.total || 0;

    // 3. Sub-Affiliate Passive Earnings (what this master gets from sub-bots)
    const subEarningsResult = await transactions.aggregate([
      { $match: { affiliate_name: affiliateName, payer_type: 'sub_affiliate' } },
      { $group: { _id: null, total: { $sum: '$wallet2_sol' } } }
    ]).toArray();
    const subEarnings = subEarningsResult[0]?.total || 0;

    // 4. Volume by Bot/Contract
    const volByContract = await transactions.aggregate([
      { $match: { affiliate_name: affiliateName } },
      {
        $group: {
          _id: '$payer_name',
          volume: { $sum: '$total_sol' },
          type: { $first: '$payer_type' }
        }
      },
      { $sort: { volume: -1 } }
    ]).toArray();

    return NextResponse.json({
      total_volume: Number(totalVolume.toFixed(4)),
      personal_earnings: Number(personalEarnings.toFixed(4)),
      sub_affiliate_earnings: Number(subEarnings.toFixed(4)),
      vol_by_contract: volByContract.map(c => ({
        name: c._id,
        volume: Number(c.volume.toFixed(4)),
        type: c.type
      }))
    });
  } catch (error) {
    console.error('Stats API error:', error);
    return NextResponse.json({ error: 'Error fetching data.' }, { status: 500 });
  }
}
